version: '3.7'

services:
  paper:
    build: .
    container_name: psychics
    stdin_open: true
    tty: true
    ports:
      - 25565:25565
      - 5005:5005
    volumes:
      - ./.docker:/data
    entrypoint:
      - /docker-setup-plugin
      - https://github.com/noonmaru/kotlin-plugin/releases/latest/download/Kotlin.jar
      - https://github.com/noonmaru/auto-reloader/releases/latest/download/InvFX.jar
      - https://github.com/noonmaru/auto-reloader/releases/latest/download/AutoReloader.jar
      - https://github.com/noonmaru/invfx/releases/latest/download/InvFX.jar
      - https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/artifact/target/ProtocolLib.jar
